#配置服务
server:
  port: 9001
#spring配置
spring:
  application:
    name: hrm-company  #服务名称
  #数据库连接池配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 111111
  #JPA配置
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true

